### ISSUE TITLE
AttributeError: Caught AttributeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Old-detective** [vision4robotics/TCTrack#39]
Traceback (most recent call last):
  File "train_tctrack.py", line 288, in <module>
    main()
  File "train_tctrack.py", line 283, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "train_tctrack.py", line 132, in train
    for idx, data in enumerate(train_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/TCTrack-main/pysot/datasets/dataset.py", line 323, in __getitem__
    current_templatebox = self._get_bbox(current_templateimage, current[0][1])
  File "/mnt/TCTrack-main/pysot/datasets/dataset.py", line 277, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Old-detective** [comment]
请问有人在训练的时候遇到过这个问题吗

**Comment by ziangcao0312** [comment]
这个问题是文件读取出现错误，image并没有被成功读取，很大可能是image路径出错，debug一下就知道了

**Comment by wolfwaytx** [comment]
@ziangcao0312
我也出现了同样的报错 经过debug后发现在
`        current_templateimage=cv2.imread(current[0][0])
        current_searchimg=cv2.imread(current[1][0])`
中current_templateimage和current_searchimg获取到的信息为None 但是我单独写了一个test 代入同样的image路径和以上的代码 发现是可以读取到数据的（非None） 请问该如何解决呢
