### ISSUE TITLE
RuntimeError: shape '[70, 4, 256, 26, 26]' is invalid for input of size 72683520

### ISSUE THREAD

**Issue by hao666liu** [vision4robotics/TCTrack#48]
请问作者以下问题怎么解决？
Traceback (most recent call last):
  File "E:/liuxinhao/python_project/TCTrack-main/tools/train_tctrack.py", line 286, in <module>
    main()
  File "E:/liuxinhao/python_project/TCTrack-main/tools/train_tctrack.py", line 281, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "E:/liuxinhao/python_project/TCTrack-main/tools/train_tctrack.py", line 169, in train
    outputs = model(data)
  File "D:\anaconda\envs\siam_track\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda\envs\siam_track\lib\site-packages\torch\nn\parallel\data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "D:\anaconda\envs\siam_track\lib\site-packages\torch\nn\parallel\data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "D:\anaconda\envs\siam_track\lib\site-packages\torch\nn\parallel\parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "D:\anaconda\envs\siam_track\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "D:\anaconda\envs\siam_track\lib\site-packages\torch\nn\parallel\parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "D:\anaconda\envs\siam_track\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\liuxinhao\python_project\TCTrack-main\pysot\models\utile_tctrack\model_builder.py", line 135, in forward
    xf.size(-1))z
**RuntimeError: shape '[70, 4, 256, 26, 26]' is invalid for input of size 72683520

**Comment by ziangcao0312** [comment]
通道数目错了，72683520对应的是（70 6 256 26 26）的特征纬度，请检查一下对应setting

**Comment by 852653835** [comment]
请问怎么解决的，调了哪些参数

**Comment by KamanRider2333** [comment]
默认设置里是2个GPU，在config.yaml文件里改成1个GPU，NUM_GPU: 1
