### ISSUE TITLE
请问有遇到过这种问题吗？

### ISSUE THREAD

**Issue by 852653835** [vision4robotics/TCTrack#51]
Traceback (most recent call last):
  File "tctrack_original/tools/train_tctrackpp.py", line 303, in <module>
    main()
  File "tctrack_original/tools/train_tctrackpp.py", line 298, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "tctrack_original/tools/train_tctrackpp.py", line 187, in train
    outputs = model(data,videorange)
  File "tctrack/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "tctrack/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "tctrack/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "tctrack/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "tctrack/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "tctrack/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "tctrack/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "tctrack_original/pysot/models/utile_tctrackplus/model_builder.py", line 142, in forward
    loc,cls2,cls3=self.grader(xf[:,-1,:,:,:],zf,xf[:,:-1,:,:,:].permute(1,0,2,3,4))
  File "tctrack/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "tctrack_original/pysot/models/utile_tctrackplus/utile.py", line 99, in forward
    ppres=self.conv1(self.xcorr_depthwise(px[0],z))
  File "tctrack_original/pysot/models/utile_tctrackplus/utile.py", line 88, in xcorr_depthwise
    x = x.reshape(1, batch*channel, x.size(2), x.size(3))
RuntimeError: shape '[1, 8960, 26, 26]' is invalid for input of size 12113920

**Comment by Wang123z** [comment]
跑过tctrack，还没跑过plus

**Comment by LIU-coder79** [comment]
请问解决了吗，我也遇到一样的问题

**Comment by Wang123z** [comment]
> 请问解决了吗，我也遇到一样的问题
这个代码复现不出来论文的效果
